const s1 = Symbol('F uria')
const s2 = Symbol('sla')
console.log(s1)
console.log(typeof(s1))
console.log(s1 == s2)
console.log(s1 === s2)
console.log(Symbol.keyFor(s1))
console.log(Symbol.keyFor(s2))

const s3 = Symbol.for('simbolo')
const s4 = Symbol.for('simbolo')
const s5 = Symbol.for('simbolo diferente')
const s6 = Symbol()
console.log(s3 === s4)
console.log(s4 === s5)
console.log(Symbol.keyFor(s3))
console.log(typeof(Symbol.keyFor(s3)))
console.log(Symbol.keyFor(s6))